### ISSUE TITLE
preview and live version does not show the text

### ISSUE THREAD

**Issue by egonw** [jacobwindsor/MetabMaster#5]
![image](https://cloud.githubusercontent.com/assets/26721/24996874/cff5fd18-2034-11e7-9f61-3896b72375e7.png)

But if I push edit, there actually is content. This is for all of the online content. The Chrome console does not show errors, tho, so I cannot give you much to go on.

**Comment by jacobwindsor** [comment]
Yep, i introduced that bug just before I left yesterday and only realised
after i deployed it. Will fix it shortly.

**Comment by jacobwindsor** [comment]
Should be fixed now. I had a few problems with observables (there's a lot of them!). There may still be some issues and am working on tidying up the code now. I'll close this issue for now but please let me know if you find something else.

The fix is currently being built and will be available via the url in ~5 minutes.
